name: pusher_channel_reverb
description: Pusher Channels Flutter Plugin For Laravel Reverb and more
version: 1.0.2
homepage: https://github.com/JITHIN665/pusher_channel_reverb.git
environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.pusher.channels_flutter
        pluginClass: PusherChannelsFlutterPlugin
        fileName: pusher_channel_reverb_flutter.dart
      ios:
        pluginClass: PusherChannelsFlutterPlugin
      web:
        pluginClass: PusherChannelsFlutterWeb
        fileName: pusher_channel_reverb_flutter_web.dart
